### ISSUE TITLE
Hide Footer, SIdebar, Header when user selects PRINT

### ISSUE THREAD

**Issue by krowvin** [USACE/groundwork#90]
Use the tailwind `print:hidden` on these various components. 

I can't see any reason we wouldn't want to enable this globally. 

This will make printing reports and similar pages easier for end users since they don't  have to deal with @media tags themselves. 

Something like this worked for one user to show a report without headers for now:

```css
@media print {
  .header_banner_container, 
  header, 
  footer, 
  .gw-hidden, 
  ol.gw-hide-scrollbar {
   display: none!important;
  }
```

In order they are
Gov banner, 
Header, 
Footer, 
Sidebar (hides on mobile)
Breadcrumbs
